name: mem-esdb

on:
  push:
    branches: [main]
    paths:
      - mem-esdb/**
      - .github/workflows/mem-esdb.yaml
  pull_request:
    branches: [main]
    paths:
      - mem-esdb/**
      - .github/workflows/mem-esdb.yml

defaults:
  run:
    working-directory: ./mem-esdb

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
                  # cache: 'yarn' # can't use cache yet as it looks for lockfile in workspace and not workdir and fails for monorepos
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install the dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test
